### ISSUE TITLE
Execution exception "Bad credentials" when run with local project

### ISSUE THREAD

**Issue by ghost** [KyleU/scala-js-typescript#2]
Tried to use this for some TypeScript definitions, run with sbt from cloned version. The server starts up fine, but I get the below exception when selecting `Project List` in the root window. Seems to want to access the DefinitelyScala github repos. Grateful for any hints!

![screenshot from 2017-12-13 19-40-45](https://user-images.githubusercontent.com/26198204/33959094-5501227a-e03e-11e7-809b-87324b67ba7b.png)

**Comment by mkotsbak** [comment]
I get the same issue...

**Comment by kyleu** [comment]
It took almost eight months, but I finally fixed it :) It now gives a meaningful error, asking for an environment variable containing any valid github api key
