### ISSUE TITLE
Scala.js 1.0

### ISSUE THREAD

**Issue by kyleu** [KyleU/scala-js-typescript#4]
Upgrade projects and republish

**Comment by virtualirfan** [comment]
I just manually upgraded scala-js-auth0js to scala.js 1.0.0-M3 and tested with a project via a publishLocal. Seems to work.

See [my fork](https://github.com/virtualirfan/scala-js-auth0js) for what I hope can be a common recipe for the upgrade of all the packages.

**Comment by kyleu** [comment]
ScalJS 1.0 still isn't finalized, but I've got the projects cross-building with M5. Still trying to figure out how to publish them, bintray isn't the right solution.
